/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGerarRouteImport } from './routes/_authenticated/gerar'
import { Route as AuthenticatedProvasRouteImport } from './routes/_authenticated/provas'
import { Route as AuthenticatedResultadosRouteImport } from './routes/_authenticated/resultados'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerarRoute = AuthenticatedGerarRouteImport.update({
  id: '/gerar',
  path: '/gerar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvasRoute = AuthenticatedProvasRouteImport.update({
  id: '/provas',
  path: '/provas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultadosRoute = AuthenticatedResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/conta': typeof AuthenticatedContaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gerar': typeof AuthenticatedGerarRoute
  '/provas': typeof AuthenticatedProvasRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/upload': typeof AuthenticatedUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/conta': typeof AuthenticatedContaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gerar': typeof AuthenticatedGerarRoute
  '/provas': typeof AuthenticatedProvasRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/upload': typeof AuthenticatedUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gerar': typeof AuthenticatedGerarRoute
  '/_authenticated/provas': typeof AuthenticatedProvasRoute
  '/_authenticated/resultados': typeof AuthenticatedResultadosRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/conta'
    | '/dashboard'
    | '/gerar'
    | '/provas'
    | '/resultados'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/conta'
    | '/dashboard'
    | '/gerar'
    | '/provas'
    | '/resultados'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/conta'
    | '/_authenticated/dashboard'
    | '/_authenticated/gerar'
    | '/_authenticated/provas'
    | '/_authenticated/resultados'
    | '/_authenticated/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerar': {
      id: '/_authenticated/gerar'
      path: '/gerar'
      fullPath: '/gerar'
      preLoaderRoute: typeof AuthenticatedGerarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provas': {
      id: '/_authenticated/provas'
      path: '/provas'
      fullPath: '/provas'
      preLoaderRoute: typeof AuthenticatedProvasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resultados': {
      id: '/_authenticated/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof AuthenticatedResultadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGerarRoute: typeof AuthenticatedGerarRoute
  AuthenticatedProvasRoute: typeof AuthenticatedProvasRoute
  AuthenticatedResultadosRoute: typeof AuthenticatedResultadosRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGerarRoute: AuthenticatedGerarRoute,
  AuthenticatedProvasRoute: AuthenticatedProvasRoute,
  AuthenticatedResultadosRoute: AuthenticatedResultadosRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
